VirtoCommerce/vc-module-profile-experience-api

- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/VirtoCommerce.ProfileExperienceApiModule.Web.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.ProfileExperienceApiModule.Tests/VirtoCommerce.ProfileExperienceApiModule.Tests.csproj
> PT-5666: Update XAPI dependencies

- .github/workflows/main.yml
- .github/workflows/publish_nugets.yml
- Directory.Build.props
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/VirtoCommerce.ProfileExperienceApiModule.Web.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.ProfileExperienceApiModule.Tests/VirtoCommerce.ProfileExperienceApiModule.Tests.csproj
> PT-1956: Bump .Net up to 6

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/IMemberAggregateRoot.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/MemberAggregateRootBase.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/DeleteMemberAddressesCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/DeleteMemberAddressesCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/MemberCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputDeleteMemberAddressType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
> ST-916: Remove member address

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/MemberAggregateRootBase.cs
Fix deleting customer addresses
> PT-7024: Fix deleting customer addresses

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/IdentityErrorType.cs
https://virtocommerce.atlassian.net/browse/ST-1542
> ST-1542: Allow the discription of Identity error can be null

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
https://virtocommerce.atlassian.net/browse/PT-6819
> fix authorization check for updateMemberAddressesCommand

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
Disposing of the user manager
https://virtocommerce.atlassian.net/browse/PT-7240
> PT: 7240: Disposing of the user manager

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
Saving of company and customer email
https://virtocommerce.atlassian.net/browse/PT-7753
https://virtocommerce.atlassian.net/browse/PT-7757
> PT-7753: Saving of company and customer email

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterCompanyCommandHandler.cs
Add contact registration notification
https://virtocommerce.atlassian.net/browse/PT-7747
> PT-7747: Add contact registration notification

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterOrganizationType.cs
https://virtocommerce.atlassian.net/browse/PT-8249
> PT-8249: Fix dynamic properties resolve for requestRegistration

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputMemberAddressType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/MemberAddressType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
https://virtocommerce.atlassian.net/browse/PT-8487
> PT-8487: Add Description field to MemberAddressType

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputMemberAddressType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-4414
> PT-4414: Set Country Name Not Required

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
Multiple users invitation fix
https://virtocommerce.atlassian.net/browse/PT-8551
> PT-8551: Multiple users invitation fix

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/AccountCreationResult.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/RegistrationError.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/AccountCreationResultType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegistrationErrorType.cs
Errors output is extended for the registration request
https://virtocommerce.atlassian.net/browse/PT-8013
> PT-8013: Errors output is extended for the registration request

- docs/index.md
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Configuration/FrontendSecurityOptions.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Services/AccountsService.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Services/IAccountService.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Web/Module.cs
Get organization maintainer role name from app settings
https://virtocommerce.atlassian.net/browse/PT-8715
> PT-8715: Get organization maintainer role name from app settings

- .github/workflows/module-ci.yml
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputInviteUserType.cs
Possibility of roles assignment to the invited user
https://virtocommerce.atlassian.net/browse/PT-8641
> PT-8641: Possibility of roles assignment to the invited user

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/NotificationRequest.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/RegisterOrganizationNotificationRequest.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/InputRequestRegistrationType.cs
Notification language parameter for the registration request
https://virtocommerce.atlassian.net/browse/PT-8019
> PT-8019: Notification language parameter for the registration request

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Middlewares/LoadUserToEvalContextMiddleware.cs
https://virtocommerce.atlassian.net/browse/PT-9138
> PT-9138: load customer's parent organizations user groups in price evaluation middleware

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/UserType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/VirtoCommerce.ProfileExperienceApiModule.Web.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-9274
> PT-9274: add login on behalf Operator field in User Type

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
Use distinct emails in the invite user mutation
https://virtocommerce.atlassian.net/browse/PT-9051
> PT-9051: Use distinct emails in the invite user mutation

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Validators/AccountValidator.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Validators/AddressValidator.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Web/Module.cs
Add email validation for organization address
https://virtocommerce.atlassian.net/browse/PT-8680
> PT-8680: Add email validation for organization address

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
Fix anonymous access to mutations createUser, createContact, createOrganization
Fix Null reference in requestRegistration mutation
https://virtocommerce.atlassian.net/browse/PT-9447
https://virtocommerce.atlassian.net/browse/PT-9440
> PT-9440: Fix anonymous access to mutations createUser, createContact, createOrganization

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputUpdateContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputUpdateOrganizationType.cs
fix: Sonar bugs
https://virtocommerce.atlassian.net/browse/PT-9455
> PT-9455: Sonar bugs

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UpdateOrganizationCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UpdateOrganizationCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/Exp/ExpOrganization.cs
- tests/VirtoCommerce.ProfileExperienceApiModule.Tests/Handlers/UpdateOrganizationCommandHandlerTests.cs
https://virtocommerce.atlassian.net/browse/PT-9501
> PT-9501: add partial update to organization update mutation

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-9494
> PT-9494: delete empty contact

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/AddressTypeEnum.cs
https://virtocommerce.atlassian.net/browse/PT-10238
> PT-10238: add Undefined address type

- Directory.Build.props
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Queries/RequestPasswordResetQueryHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
- Update ExperienceApi module version
- Remove using obsolete interfaces for services
> Update ExperienceApi version, remove obsolete

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
fix: Anonymous has access to list of contacts or organizations
https://virtocommerce.atlassian.net/browse/PT-11496
> PT-11496: Anonymous has access to list of contacts or organizations

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ChangePasswordCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ChangePasswordCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ResetPasswordByTokenCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputChangePasswordType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/UserType.cs
```js
mutation changePassword ($command: InputChangePasswordType!) {
changePassword (command: $command) {
succeeded
errors {
description
}
}
}
```
https://virtocommerce.atlassian.net/browse/PT-12147
> PT-1214: add force password change flag to user type and 'change password' mutation

- .editorconfig
- Directory.Build.props
- VirtoCommerce.ProfileExperienceApiModule.sln.DotSettings
- module.ignore
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/SendVerifyEmailCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Queries/RequestPasswordResetQueryHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/Module.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Web/VirtoCommerce.ProfileExperienceApiModule.Web.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.ProfileExperienceApiModule.Tests/VirtoCommerce.ProfileExperienceApiModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-10449
> PT-10449: Use updated Crud and Search services

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ConfirmEmailCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ConfirmEmailCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/SendRegistrationNotificationCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/SendRegistrationNotificationCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/SendVerifyEmailCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Extensions/StoreExtensions.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/AccountCreationResult.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/ModuleConstants.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputConfirmEmailType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/AccountCreationResultType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-12829
> PT-12829: add email registrations flows

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/AccountCreationResult.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Services/AccountsService.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Services/IAccountService.cs
https://virtocommerce.atlassian.net/browse/PT-13140
> PT-13140: cleanup organization and contact on account creation error

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ConfirmEmailCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/LockOrganizationContactCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UnlockOrganizationContactCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Services/AccountsService.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Services/IAccountService.cs
https://virtocommerce.atlassian.net/browse/PT-12906
> PT-12906: modify lock/unlock operations

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ConfirmEmailCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Extensions/StoreExtensions.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/AccountCreationResult.cs
- Make ConfirmEmailCommandHandler methods protected
- Refactoring register request notifications
> Refactoring user register notifications

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/UserType.cs
```
{
me {
passwordExpiryInDays
}
}
```
https://virtocommerce.atlassian.net/browse/PT-12811
> PT-12811: add passwordExpiryInDays field

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterByInvitationCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-13378
> PT-13378: verify email on register by invitation

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
feat: Returns correct authorization error codes
Code | Message | Recommended Action
-- | -- | --
Unauthorized | Anonymous access denied or access token has expired or is invalid. | Redirect to Signin page
Forbidden | Access denied. | Display Access Denied page
Forbidden | User doesn't have the required permission 'name'. | Display Access Denied page
UserLocked | This user is locked. | Display Error page
PasswordExpired | This user has their password expired. Please change the password using   'changePassword' command. | Open Change Password form
https://virtocommerce.atlassian.net/browse/PT-13290
> PT-13290: Use correct authorization error codes

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Mapping/ProfileMappingProfile.cs
https://virtocommerce.atlassian.net/browse/PT-13804
> PT-13804: create Member types via AbstractTypeFactory

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
https://virtocommerce.atlassian.net/browse/PT-14272
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.412.0-pr-63-9105.zip
> PT-14272: add FirstName to new invited contact

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterByInvitationCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/ModuleConstants.cs
https://virtocommerce.atlassian.net/browse/PT-14331
https://virtocommerce.atlassian.net/browse/PT-12594
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.413.0-pr-64-72c0.zip
> PT-14331: Update contact status when using invitation

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/LockOrganizationContactCommandHandler.cs
Adding the virtual attribute to the handle method in the LockOrganizationContactCommand mutation
https://virtocommerce.atlassian.net/browse/PT-15125
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.416.0-pr-68-bdfe.zip
> feat: Adding the virtual attribute to the handle method in the LockOrganizationContactCommand mutation

- Directory.Build.props
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/VirtoCommerce.ProfileExperienceApiModule.Web.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.ProfileExperienceApiModule.Tests/VirtoCommerce.ProfileExperienceApiModule.Tests.csproj
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.800.0-pr-67-44f7.zip
> PT-14740: update to .NET8

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ConfirmEmailCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterByInvitationCommandHandler.cs
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.801.0-pr-69-ac08.zip
> fix: remove cancellationTokenSource

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
fix: An issue was identified where the anonymous cart was being reset upon browser refresh. Virto Storefront, Virto Commerce Experience and Profile Experience module should be updated as well.
https://virtocommerce.atlassian.net/browse/VCST-192
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.803.0-pr-72-8ca9.zip
> VCST-192: Anonymous Cart Reset Issue Upon Browser Refresh

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
This extension is necessary for override to be able to create contacts, to fill in additional fields before saving
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.804.0-pr-74-a354.zip
> feat: Extend InviteUserCommandHandler to include a virtual method for creating a contact.

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterByInvitationCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-885
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.805.0-pr-76-909c.zip
> VCST-885: check contact lock on register by invitation

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ContactCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputContactBaseType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
```
query me {
me {
contact {
defaultLanguage
currencyCode
}
}
}
```
```
mutation updateContact ($command: InputUpdateContactType!) {
updateContact (command: $command) {
id
defaultLanguage
currencyCode
}
}
```
https://virtocommerce.atlassian.net/browse/VCST-1277
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.806.0-pr-75-ed3f.zip
> VCST-1277: add currency code to Contact

- module.ignore
- module.keep
- src/VirtoCommerce.ProfileExperienceApiModule.Web/Module.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-1543
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.811.0-pr-82-6803.zip
> VCST-1543: add optional modules attribute

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/MemberBaseType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterOrganizationType.cs
https://virtocommerce.atlassian.net/browse/VCST-1627
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.812.0-pr-83-7118.zip
> VCST-1627: make member address schema extendable

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Mapping/ProfileMappingProfile.cs
Send empty addresses list to erase all contact addresses.
https://virtocommerce.atlassian.net/browse/VCST-1647
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.814.0-pr-86-b786.zip
> VCST-1647: skip mapping addresses on update contact if addresses == null

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-1636
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.813.0-pr-84-b299.zip
> VCST-1636: use AbstractTypeFactory to create ApplicationUser

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-1663
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.815.0-pr-87-bf87.zip
> VCST-1663: change user type to Customer for Register Request Command

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
https://virtocommerce.atlassian.net/browse/VCST-1762
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.816.0-pr-89-3dbf.zip
> VCST-1762: Add 'userId' argument to 'me' query

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
feat: Replace custom code with ClaimsPrincipalExtensions that resolves user id and name from IdentityOptions settings.
https://virtocommerce.atlassian.net/browse/VCST-2048
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.818.0-pr-90-25cb.zip
> VCST-2048: Use ClaimsPrincipalExtensions GetUserId

- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/Module.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
playground url: /ui/playground/profile
https://virtocommerce.atlassian.net/browse/VCST-2241
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.819.0-pr-91-62e4.zip
> VCST-2241: add scoped schema

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ConfirmEmailCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-2404
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.820.0-pr-92-9eae.zip
> VCST-2404: ignore user reconfirmation

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UpdateContactCommandHandler.cs
With the mapping logic isolated, it will be simpler to modify or extend the behavior in the future (for example, handling additional extended properties or custom mapping scenarios) without affecting the overall handler logic.
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.901.0-pr-94-b3c0.zip
> UpdateContactCommandHandler Extract Mapping Logic into Separate Method

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/InviteUserCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterByInvitationCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/ResetPasswordByTokenCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Queries/RequestPasswordResetQueryHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-2644
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.903.0-pr-96-b5bd.zip
> VCST-2644: restrict password reset

- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2589
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.904.0-pr-97-5f50.zip
> VCST-2589: update Xapi dependency (Mediatr)

- module.keep
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UserCommandHandlerBase.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-2047
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.909.0-pr-104-78dd.zip
> VCST-2047: Make VirtoCommerce.Tax optional

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/Contact/ContactAggregate.cs
We noticed that condition should be improved since we encountered a scenario where Contact was null and the if condition was allowing it to continue creating an exception at line 18
> Fix null condition in ContactAggregate.cs

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/Contact/ContactAggregate.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Aggregates/MemberAggregateRootBase.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Authorization/ProfileAuthorizationHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UserCommandHandlerBase.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Queries/GetUserQueryHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ContactType.cs
https://virtocommerce.atlassian.net/browse/VCST-3119
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.911.0-pr-106-14f5.zip
> VCST-3119: Set default language and currency to new contacts

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Mapping/ProfileMappingProfile.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Models/RegisterOrganization/RegisteredOrganization.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/InputRegisterOrganizationType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterOrganizationType.cs
https://virtocommerce.atlassian.net/browse/VCST-3200
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.912.0-pr-107-392f.zip
> VCST-3200: add phone number to request registration organization

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UpdateContactCommand.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/UpdateContactCommandHandler.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputContactBaseType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputUpdateContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/InputUpdateOrganizationType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/ProfileSchema.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
- tests/VirtoCommerce.ProfileExperienceApiModule.Tests/Handlers/UpdateContactCommandHandlerTests.cs
https://virtocommerce.atlassian.net/browse/VCST-3294
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.916.0-pr-113-16a7.zip
> VCST-3294: Save selected address for each organization

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/MemberBaseType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterContactType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/Schemas/RegisterCompany/RegisterOrganizationType.cs
- src/VirtoCommerce.ProfileExperienceApiModule.Data/VirtoCommerce.ProfileExperienceApiModule.Data.csproj
- src/VirtoCommerce.ProfileExperienceApiModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VCST-3299
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.917.0-pr-112-8a8b.zip
> VCST-3299: Update references to modules which use SEO

- src/VirtoCommerce.ProfileExperienceApiModule.Data/Commands/RegisterRequestCommandHandler.cs
https://virtocommerce.atlassian.net/browse/VCST-3623
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ProfileExperienceApiModule_3.921.0-pr-114-76f8.zip
> VCST-3623: Skip operation canceling when error isn't critical
